spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.31.206:3306/aihudb?ucharacterEncoding=UTF8
    username: builder
    password: builder@123
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没有可用的连接则发生SQLException，默认30秒
      connection-timeout: 30000
      # 最小连接数
      minimum-idle: 5
      # 最大连接数
      maximum-pool-size: 15
      # 自动提交
      auto-commit: true
      # 一个连接idle状态的最大时长（毫秒），超时则被释放（retired),默认10分钟
      idle-timeout: 600000
      # 连接池的名称
      pool-name: DatebookHikariCP
      # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired),默认30分钟1800000ms
      max-lifetime: 28740000
      connection-test-query: SELECT 1