############################################################
#
# web访问端口号  约定：8088
#
############################################################
server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB
#  servlet:
#    context-path: /mvc


############################################################
#
# 配置数据源信息
#
############################################################
spring:
  profiles:
    active: mysql
  application:
    name: aihushop-api


mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  config: classpath:logback-spring.xml


springfox:
  documentation:
    swagger-ui:
      base-url: /documentation
    swagger:
      v2:
        use-model-v3: false
