# 数据源
spring:
  datasource:
    driver-class-name: org.h2.Driver
    schema: classpath:db/schema-h2.sql
    data: classpath:db/data-h2.sql
    url: jdbc:h2:file:F:\A-wangbinbin\workSpace\aihushop\auhushop-api\src\main\resources\db;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1
    #url: jdbc:h2:file:./src/main/resources/db/sqlData
    username: sa
    password: 123456
    initialization-mode: always

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  h2:
    console:
      path: /h2-console
      enabled: true
      settings:
        web-allow-others: true